MavGymService/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView, PasswordChangeDoneView, PasswordChangeView
from django.urls import path, re_path
from django.conf.urls import include,url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gym.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    re_path(r'^accounts/login/$', LoginView.as_view(template_name='registration/login.html'), name="login"),
    re_path(r'^accounts/logout/$', LogoutView.as_view(template_name='registration/logout.html'), LogoutView.next_page,
            name="logout"),
    re_path(r'^accounts/password/change/$',
            PasswordChangeView.as_view(template_name='registration/change-password.html'), name='password_change'),
    re_path(r'^accounts/password/change/done/$',
            PasswordChangeDoneView.as_view(template_name='registration/change-password-done.html'),
            name='password_change_done'),
re_path(r'^accounts/password/reset/$',
            PasswordResetView.as_view(template_name='registration/password_reset_page.html'), name='password_reset'),
    re_path(r'^accounts/password/reset/done/$',
            PasswordResetDoneView.as_view(template_name='registration/passwordreset_pagedone.html'),
            name='password_reset_done'),
    re_path(
        r'^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
        PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirmpage.html'),
        name='password_reset_confirm'),
    re_path(r'^accounts/password/reset/complete/$',
            PasswordResetCompleteView.as_view(template_name='registration/password_reset_completepage.html'),
            name='password_reset_complete'),

]

gym/urls.py
from . import views
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView, LogoutView


app_name = 'gym'
urlpatterns = [
    path('', views.home, name='home'),
    url(r'^home/$', views.home, name='home'),
    path('register/', views.register, name='register'),
    url(r'^About/$', views.About, name='About'),
    path('contact/', views.contact, name='contact'),
    url ( r'^calendar/$' , views.CalendarView.as_view ( ) , name='calendar' ) ,
    url ( r'^event/new/$' , views.event_new , name='event_new' ) ,
    url ( r'^event/edit/(?P<event_id>\d+)/$' , views.event_edit , name='event_edit' ) ,
    path ( r'^event/<int:pk>/delete/' , views.event_delete , name='event_delete' ) ,
    url ( r'^customercalendar/$' , views.CalendarCustomerView.as_view ( ) , name='customercalendar' ) ,
    path('CustomerViewActivities', views.CustomerViewActivities, name='CustomerViewActivities'),
    path('admin/users_list', views.users_list, name='users_list'),
    path('user/<int:pk>/edit/', views.user_edit, name='user_edit'),
    path('user/<username>/delete/', views.user_delete, name='user_delete'),
    path('user/create/', views.user_new, name='user_new'),
    url(r'^reports_list/$', views.reports_list, name='reports_list'),
    path('user_summary_pdf', views.user_summary_pdf, name='user_summary_pdf'),
    path('activities_summary_pdf', views.activities_summary_pdf, name='activities_summary_pdf'),
    path('equipment_list', views.equipment_list, name='equipment_list'),
    path('equipment/<int:pk>/edit/', views.equipment_edit, name='equipment_edit'),
    path('equipment/<int:pk>/delete/', views.equipment_delete, name='equipment_delete'),
    path('equipment/create/', views.equipment_new, name='equipment_new'),
    path('CustomerViewEquipments', views.CustomerViewEquipments, name='CustomerViewEquipments'),
    path('equipment_summary_pdf', views.equipment_summary_pdf, name='equipment_summary_pdf'),


    ]

gym/forms.py
from django import forms
from django.forms import ModelForm, DateInput
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Availability, GymEquipment

class RegisterForm(UserCreationForm):
    password1 = forms.CharField(label='Password',
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                                widget=forms.PasswordInput)
    email = forms.EmailField(label='Email', max_length=254, help_text='Required. Enter a valid email address.')
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)

    class Meta:
        model = User
        fields = ('username','email', 'first_name','last_name','password1','password2')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

class DateInput(forms.DateInput):
    input_type = "date"

    def __init__(self, **kwargs):
        kwargs["format"] = "%Y-%m-%d"
        super().__init__(**kwargs)

class EventForm(forms.ModelForm):
  class Meta:
    model = Availability
    widgets = {
      'start_date': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M')
    }
    fields = ['activity','time','location','start_date']

  def __init__ ( self , *args , **kwargs ) :
      super ( EventForm , self ).__init__ ( *args , **kwargs )
      self.fields['start_date'].widget = DateInput()

class EventEditForm(forms.ModelForm):
  class Meta:
    model = Availability
    widgets = {
      'start_date': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M')
    }
    fields = ['activity','time','location','start_date']

  def __init__ ( self , *args , **kwargs ) :
      super ( EventEditForm , self ).__init__ ( *args , **kwargs )
      self.fields['start_date'].widget = DateInput()
      self.fields['start_date'].disabled = True

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username')


class ContactForm(forms.Form):
    Name = forms.CharField(required=True)
    Email = forms.EmailField(required=True)
    Subject = forms.CharField(required=False)
    Message = forms.CharField(
    required=True,
    widget=forms.Textarea)

class EquipmentEditForm(forms.ModelForm):
    class Meta:
        model = GymEquipment
        fields = ('name', 'description', 'weight')

gym/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.utils.safestring import mark_safe
from django.views import generic
from .forms import RegisterForm , EventForm , EventEditForm
from .models import *
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import permission_required
from django.shortcuts import redirect
import calendar
from .forms import User
from .forms import Availability
from .utils import Calendar,CustomerCalendar
from datetime import datetime, timedelta, date
from django.urls import reverse
from .forms import UserEditForm
from django.template.loader import get_template
from .utils import render_to_pdf
from .forms import *
from django.db.models import Q



now = timezone.now()
def home(request):
   return render(request, 'gym/home.html',
                 {'gym': home})

def register(request):
    print("entered into register view method")
    if request.method == 'POST':
        print("entered into register view method entered if method")
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request,
                          'registration/registerdone.html',
                          {'form': form})
    else:
        form = RegisterForm()
    return render(request, "registration/register.html", {"form": form})


class CalendarView(generic.ListView):
    model = Availability
    template_name = 'gym/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        staff = Staff.objects.get(staff_name_id=self.request.user.id)
        cal = Calendar(d.year, d.month, staff.id)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context


class CalendarCustomerView(generic.ListView):
    model = Availability
    template_name = 'gym/viewCalendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = CustomerCalendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['customercalendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context


def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

def event_new(request, event_id=None):
    instance = Availability()
    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        availform = form.save ( commit=False )
        staff=Staff.objects.get ( staff_name_id=request.user.id )
        availform.availability_staff_name_id = staff.id
        today = date.today()
        first_day = today.replace(day=1)
        thisMonthDate = first_day
        #alreadyDataCount = Availability.objects.filter ( availability_staff_name_id = staff.id,start_date= availform.start_date).count ( )
        #if(alreadyDataCount==0):
        if (availform.start_date >= thisMonthDate):
            availform.save ( )
            return HttpResponseRedirect ( reverse ( 'gym:calendar' ) )
        else:
            messages.error ( request , 'Cannot add availability for previous month..' )
            return render(request, 'gym/event.html', {'form': form})

    return render(request, 'gym/event.html', {'form': form})

def event_edit(request, event_id):

    instance = get_object_or_404(Availability, pk=event_id)
    form = EventEditForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        availform = form.save ( commit=False )
        staff=Staff.objects.get ( staff_name_id=request.user.id )
        availform.availability_staff_name_id = staff.id
        availform.save ( )
        return HttpResponseRedirect ( reverse ( 'gym:calendar' ) )
    return render(request, 'gym/event.html', {'form': form})

def event_delete(request,pk):
    instance = Availability ( )
    event = get_object_or_404 ( Availability , pk=pk )
    event.delete ( )
    return HttpResponseRedirect(reverse('gym:calendar'))

@login_required
def CustomerViewActivities(request):
    availabilities = Availability.objects.filter(created_date__lte=timezone.now())
    return render(request, 'gym/CustomerViewActivities.html',
                 {'availabilities': availabilities})

@login_required
def users_list(request):
    users = User.objects.all()
    #print(users)
    return render(request, 'gym/users_list.html', {'users': users})

@login_required
def user_edit(request, pk):
   user = get_object_or_404(User, pk=pk)
   if request.method == "POST":
       # update
       form = UserEditForm(request.POST, instance=user)
       if form.is_valid():
           user = form.save(commit=False)
           user.updated_date = timezone.now()
           user.save()
           users = User.objects.filter()
           print(users)
           return render(request, 'gym/users_list.html',
                         {'users': users})
   else:
        # edit
       form = UserEditForm(instance=user)
       return render(request, 'gym/user_edit.html', {'form': form})

@login_required
def user_delete(request, username):
    users = User.objects.get(username=username)
    users.delete()
    return redirect('gym:users_list')

@login_required
def user_new(request):
   if request.method == "POST":
       form = UserEditForm(request.POST)
       if form.is_valid():
           newuser = form.save(commit=False)
           newuser.date_joined = timezone.now()
           newuser.save()
           users = User.objects.filter(date_joined__lte=timezone.now())
           return render(request, 'gym/users_list.html',
                         {'users': users})
   else:
       form = UserEditForm()
       # print("Else")
   return render(request, 'gym/user_new.html', {'form': form})


@login_required
def reports_list(request):
    return render(request, 'gym/reports_list.html',
                  {'gym': reports_list})


@login_required
def user_summary_pdf(request):
    users = User.objects.all()
    context = {'users': users,}
    template = get_template('gym/user_summary_pdf.html')
    html = template.render(context)
    pdf = render_to_pdf('gym/user_summary_pdf.html', context)

    return pdf


@login_required
def activities_summary_pdf(request):
    availabilities = Availability.objects.filter(created_date__lte=timezone.now())
    context = {'availabilities': availabilities,}
    template = get_template('gym/activities_summary_pdf.html')
    html = template.render(context)
    pdf = render_to_pdf('gym/activities_summary_pdf.html', context)
    return pdf

def contact(request):
    form_class = ContactForm

    return render(request, 'registration/contact.html', {'form': form_class})


@login_required
def equipment_list(request):
    equipments = GymEquipment.objects.all()
    return render(request, 'gym/equipment_list.html', {'equipments': equipments})



@login_required
def equipment_edit(request, pk):
   equipment = get_object_or_404(GymEquipment, pk=pk)
   if request.method == "POST":
       # update
       form = EquipmentEditForm(request.POST, instance=equipment)
       if form.is_valid():
           equipment = form.save(commit=False)
           equipment.updated_date = timezone.now()
           equipment.save()
           equipments = GymEquipment.objects.filter()
           print(equipments)
           return render(request, 'gym/equipment_list.html',
                         {'equipments': equipments})
   else:
        # edit
       form = EquipmentEditForm(instance=equipment)
       return render(request, 'gym/equipment_edit.html', {'form': form})

@login_required
def equipment_delete(request, pk):
    equipments = get_object_or_404(GymEquipment, pk=pk)
    equipments.delete()
    return redirect('gym:equipment_list')

@login_required
def equipment_new(request):
   if request.method == "POST":
       form = EquipmentEditForm(request.POST)
       if form.is_valid():
           newequipment = form.save(commit=False)
           newequipment.date_joined = timezone.now()
           newequipment.save()
           equipments = GymEquipment.objects.filter()
           return render(request, 'gym/equipment_list.html',
                         {'equipments': equipments})
   else:
       form = EquipmentEditForm()
       # print("Else")
   return render(request, 'gym/equipment_new.html', {'form': form})


@login_required
def CustomerViewEquipments(request):
    equipments = GymEquipment.objects.filter()
    return render(request, 'gym/CustomerViewEquipments.html',
                 {'equipments': equipments})

@login_required
def equipment_summary_pdf(request):
    equipments = GymEquipment.objects.filter()
    context = {'equipments': equipments,}
    template = get_template('gym/equipment_summary_pdf.html')
    html = template.render(context)
    pdf = render_to_pdf('gym/equipment_summary_pdf.html', context)
    return pdf


def About(request):
   return render(request, 'gym/About.html',
                 {'vna': About})

gym/templates/gym/About.html
{% extends 'gym/base.html' %}
{% load static %}
{% block content %}
 <div class="ui main container">
 <head>
     <style>
        body {
            background-color: white;
            height: auto;
        }
        h2 {
            color:#d5242f ;
        }
     </style>
 </head>
<h2 >What We Do</h2>

     <p>Mav Gym Services provides gym facilities. It provides gym equipments and also other activities such as zumba class, Yoga class, swimming class etc.</p>
<h2>VNA service areas include:</h2>

<ul><li>Swimming Classes</li>
    <li>Zumba Classes</li>
    <li>Yoga Class</li>
    <li>Basketball Classes</li>
    <li>Dancing Classes</li>

</ul>
 </div>
{% endblock %}

gym/templates/gym/CustomerViewEquipments.html
{% extends 'gym/base.html' %}
{% load static %}
{% block content %}

    {% if user.is_authenticated %}
        <style>
        body {
            background-color: white;
        }

    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Mav Gym Service!
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="ui main container">
        <div class="page-container">
            <h2 class="top-menu">All Equipments</h2>

            <div>
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                    <tr class="bg-info">
                        <th>Name</th>
                        <th>Description</th>
                        <th>Weight</th>



                    </tr>
                    </thead>
                <tbody>
                    {% for equipments in equipments %}
                        <tr>
                            <td>{{ equipments.name }}</td>
                            <td>{{ equipments.description }}</td>
                             <td>{{ equipments.weight }}</td>

                        </tr>
                    {% endfor %}
                </tbody>
                </table>



            </div>
        </div>
        </div>
    {% endif %}


{% endblock %}

gym/templates/gym/calendar.html
{% extends 'gym/base.html' %}
{% load static %}
{% block content %}

{% comment %}<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">{% endcomment %}

<div class="clearfix">
	<a class="btn btn-info left" href="{% url 'gym:calendar' %}?{{ prev_month }}"> Previous Month </a>
	<a class="btn btn-info right" href="{% url 'gym:calendar' %}?{{ next_month }}"> Next Month </a>
	<a class="btn btn-info right" href="{% url 'gym:event_new' %}"> Add New Activity  </a>
</div>


{{ calendar }}

{% endblock %}

gym/templates/gym/equipment_edit.html
{% extends 'gym/base.html' %}
{% comment %}{% load crispy_forms_tags %}{% endcomment %}
{% block content %}
      <div class="ui main container">
    <h1>Edit Equipment</h1>
    <form method="POST" class="user-form">{% csrf_token %}
          {{ form.as_p}}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
      </div>
{% endblock %}

gym/templates/gym/equipment_list.html
{% extends 'gym/base.html' %}
{% load static %}
{% block content %}

    {% if user.is_authenticated %}
        <style>
        body {
            background-color: white;
        }

    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Mav Gym Service!
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="ui main container">
        <div class="page-container">
            <h2 class="top-menu">All Equipments</h2>

            <div>
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                    <tr class="bg-info">
                        <th>Name</th>
                        <th>Description</th>
                        <th>Weight</th>

                    <th colspan="3">Actions</th>

                    </tr>
                    </thead>
                <tbody>
                    {% for equipments in equipments %}
                        <tr>
                            <td>{{ equipments.name }}</td>
                            <td>{{ equipments.description }}</td>
                             <td>{{ equipments.weight }}</td>
                        <td><a href="{% url 'gym:equipment_edit' pk=equipments.pk %}" class="btn btn-primary">Edit</a>

                            <td><a href="{% url 'gym:equipment_delete' pk=equipments.pk %}"
                                onclick="return confirm('Are you sure you want to delete?')"
                                class="btn btn-primary">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
                </table>
            <div class="row">
                    <a href="{% url 'gym:equipment_new' %}" class="row"><span
                    class="btn btn-primary">Add Equipment</span></a>
                </div>


            </div>
        </div>
        </div>
    {% endif %}


{% endblock %}

gym/templates/gym/equipment_new.html
{% extends 'gym/base.html' %}
{% comment %}{% load crispy_forms_tags %}{% endcomment %}
{% block content %}
    <div class="ui main container">
    <h1>Add a New Equipment</h1>
    <form method="POST" class="user-form">{% csrf_token %}
          {{ form.as_p}}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
    </div>
{% endblock %}

gym/templates/gym/event.html
{% extends 'gym/base.html' %}
{% load static %}
{% block content %}

{% if messages %}
<ul style="color:mediumspringgreen;font-size: 20px;">
   {% for message in messages %}
	   <li>{{ message }}</li>
   {% endfor %}
</ul>
{% endif %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'gym:calendar' %}"> Calendar </a>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>

{% endblock %}

gym/templates/gym/home.html
{% extends "gym/base.html" %}
{% load static %}



{% block content %}
{% if user.is_authenticated and user.is_superuser %}
    <div class="ui main container">
        {% if user.is_authenticated %}
            <div class="page-container">
                <h2 class="top-menu">Welcome {{ user.username }},</h2>
                <p>Please choose from below options.</p>
            </div>
        {% endif %}

         <div class="content white-square">
            <div class="row">

                <div class="col-md-3">
                    <div class="thumbnail">
                        <h2>MANAGE USERS</h2>
                        <p><a class="btn btn-primary" href="{% url 'gym:users_list'%}" role="button">Click here </a></p>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="thumbnail">
                        <h2>MANAGE REPORTS</h2>
                        <p><a class="btn btn-primary" href="{% url 'gym:reports_list'%}" role="button">Click here </a></p>
                    </div>
                </div>


            </div>
        </div>
    </div>
         {% elif user.is_authenticated and user.groups.all.0.name == "Customer" %}
         <div class="ui main container">
        {% if user.is_authenticated %}
            <div class="page-container">
                <h2 class="top-menu">Welcome {{ user.username }},</h2>
                <p>Please choose from below options.</p>
            </div>
        {% endif %}

        <div class="content white-square">
            <div class="row">
                <div class="col-md-3">
                    <div class="thumbnail">
                        <h2>VIEW ACTIVITIES</h2>
                        <p><a class="btn btn-primary" href="{% url 'gym:CustomerViewActivities' %}" role="button">Click here </a></p>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="thumbnail">
                        <h2>VIEW EQUIPMENTS<br></h2>
                        <p><a class="btn btn-primary" href="{% url 'gym:CustomerViewEquipments' %}" role="button">Click here </a></p>
                    </div>
                </div>



            </div>
        </div>
    </div>

         {% elif user.is_authenticated and user.groups.all.0.name == "Staff" %}
         <div class="ui main container">
        {% if user.is_authenticated %}
            <div class="page-container">
                <h2 class="top-menu">Welcome {{ user.username }},</h2>
                <p>Please choose from below options.</p>
            </div>
        {% endif %}

        <div class="content white-square">
            <div class="row">
                  <div class="col-md-3">
                    <div class="thumbnail">
                        <h2>MANAGE ACTIVITIES<br></h2>
                        <p><a class="btn btn-primary" href="{% url 'gym:calendar' %}" role="button">Click here </a></p>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="thumbnail">
                        <h2>MANAGE EQUIPMENTS<br></h2>
                        <p><a class="btn btn-primary" href="{% url 'gym:equipment_list' %}" role="button">Click here </a></p>
                    </div>
                </div>




            </div>
        </div>
    </div>


                    {% else %}

                                    <!--<div class="container">-->
                                <div class="page-container">


                                <img src={% static "img/fit.jpg"%} "" style="width:100%;height:500px">

                                <div class="hero-ilwid-container--left">

                                      <div class="top-left">

                                          <h1 class="hero-ilwid" tabindex="-1"> <span style="color:whitesmoke;">Welcome to MAV GYM SERVICES</span>
                                          </h1>
                                           <a class="btn btn-primary" href="{% url "login" %}">Login Here</a>

                                        </div>
                                </div>
                                </div>

                                                            <div class="content white-square">
                                                              <div class="row">

                                                                <div class="col-md-4">
                                                                    <div class="thumbnail">

                                                                        <h2>ABOUT US</h2>
                                                                        <p>If you want to know about our organization, click below.
                                                                        <br><br>
                                                                        </p>
                                                                        <p><a class="btn btn-primary" href="{% url 'gym:About' %}"
                                                                              role="button">View
                                                                            details</a></p>
                                                                    </div>
                                                                </div>

                                                                <div class="col-md-4">
                                                                    <div class="thumbnail">

                                                                      <h2>CREATE ACCOUNT</h2>
                                                                      <p>If you want to sign up and create account with Mav Gym, click in the below link.</p>

                                                                        <p><a class="btn btn-primary" href="{% url 'gym:register' %}"
                                                                              role="button">View
                                                                            details </a></p>
                                                                    </div>
                                                                </div>
                                                                    <div class="col-md-4">
                                                                    <div class="thumbnail">


                                                                      <h2>CONTACT</h2>
                                                                      <p>If you want to know any specific details. Be sure to contact us using the link below on Mav Gym website.</p>
                                                                      <p><a class="btn btn-primary" href="{% url 'gym:contact' %}"
                                                                              role="button">View
                                                                            details</a></p>

                                                                    </div>
                                                                    </div>


                                                              </div>
                                                            </div>


 {% endif %}



{% endblock %}

gym/templates/gym/user_delete.html
{% extends 'gym/base.html' %}
 {% block body_block %}
    <h1>Delete {{ users.username }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'vna:users_list' pk=users.username %} ">Cancel</a>

    </form>

{% endblock %}

gym/templates/gym/viewCalendar.html
{% extends 'gym/base.html' %}
{% load static %}
{% block content %}
<div class="ui main container">
	<div class="clearfix">
		<a class="btn btn-info left" href="{% url 'gym:customercalendar' %}?{{ prev_month }}"> Previous Month </a>
		<a class="btn btn-info right" href="{% url 'gym:customercalendar' %}?{{ next_month }}"> Next Month </a>
	</div>

{{ staffcalendar }}
</div>
{% endblock %}